input: sensors: mc3230: set vfs-only exports into their own namespace
According to gki commit d483eed85ffb ("ANDROID: GKI: set vfs-only exports into their own namespace").

ERROR: modpost: module mc3230 uses symbol filp_open from namespace VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver, but does not import it.

Signed-off-by: Tao Huang <huangtao@rock-chips.com>
Change-Id: I29d6a1c79987dc30f4870c42e2995e7045e635ac