Included missing <strings.h>
``bcmd()`` is a function from ``<strings.h>`` (with s) that are not included in the file, so Mmy compiler throws an error:

```sh
$ make -j 8
  HOSTLD  scripts/kconfig/conf
/usr/bin/arm-linux-androideabi-ld: scripts/kconfig/confdata.o: in function `conf_write':
confdata.c:(.text+0x1484): undefined reference to `bcmp'
gcc: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [scripts/Makefile.host:116: scripts/kconfig/conf] Error 1
make[1]: *** [Makefile:567: syncconfig] Error 2
make: *** [Makefile:678: include/config/auto.conf.cmd] Error 2
```
im following [that tutorial](https://gist.github.com/EduApps-CDG/733e29c28dd53e91128d384c2e879397) that says how to compile the Kernel with a Android, but thr error is not on the tutorial, but on compile.