media: i2c: hall-dc-motor: fix compilation issue on 32bit
ERROR: "__aeabi_uldivmod" [drivers/media/i2c/hall-dc-motor.ko] undefined!

Fixes: a73b62eb5943 ("media: add hall-dc-motor driver for camera iris")
Signed-off-by: Tao Huang <huangtao@rock-chips.com>
Change-Id: I22fec672086f1187da795a510373eb3ee579e1f2