media: spi: rk1608: set vfs-only exports into their own namespace
According to gki commit d483eed85ffb ("ANDROID: GKI: set vfs-only exports into their own namespace").

ERROR: modpost: module rk1608 uses symbol kernel_write from namespace VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver, but does not import it.
ERROR: modpost: module rk1608 uses symbol kernel_read from namespace VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver, but does not import it.
ERROR: modpost: module rk1608 uses symbol filp_open from namespace VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver, but does not import it.

Signed-off-by: Tao Huang <huangtao@rock-chips.com>
Change-Id: I931ffc3ffb0a17717368da9fc65597da2bfd8eb0