ANDROID: mm: shmem: Fix build break with allnoconfig
With allnoconfig, build is breaking with below message, which is
introduced in commit daeabfe7fa04 ("ANDROID: mm: add
reclaim_shmem_address_space() for faster reclaims"). Fix it.

mm/shmem.c: In function ‘reclaim_shmem_address_space’:
mm/shmem.c:4321:7: error: implicit declaration of function
‘isolate_lru_page’ [-Werror=implicit-function-declaration]
   if (isolate_lru_page(page))

Bug: 187798288
Signed-off-by: Charan Teja Reddy <charante@codeaurora.org>
Change-Id: I27494b329e9b667869e1f5264bd319d94b8d2dd6