ANDROID: Fix wrong pr_err type specifier in add_memory_subsection
Wrong pr_err type specifier causes the following warning:
error: format ‘%lx’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘u64’ {aka ‘long long unsigned int’} [-Werror=format=]
Fix it by changing to the correct type specifyer for u64.

Fixes: 42db6c2e985b ("ANDROID: mm/memory_hotplug: implement {add/remove}_memory_subsection")
Bug: 170460867
Signed-off-by: Suren Baghdasaryan <surenb@google.com>
Change-Id: I6a59462a2a698112b97806618283a7afddb811cb
Git-commit: 81a34d6495e33236a3b00e891985c328e922f451
Git-repo: https://android.googlesource.com/kernel/common
Signed-off-by: Chris Goldsworthy <quic_cgoldswo@quicinc.com>