arm64/configs: enable CONFIG_SQUASHFS_XZ for rockchip_linux_defconfig
This patch enabled CONFIG_SQUASHFS_XZ that includes support for reading
Squashfs file systems compressed with XZ compression. XZ gives better
compression than the default zlib compression, that enable it on linux
platform by default.

The snap can't work issue that found on some popular latest llnux OS,
as below error log with snap.

$snap install hello-world

Filesystem uses "xz" compression. This is not supported
error: system does not fully support snapd: cannot mount squashfs image
using "squashfs": mount: /tmp/sanity-mountpoint-583983220: wrong fs type,
bad option, bad superblock on /dev/loop0, missing codepage or helper
program, or other error.

Signed-off-by: Caesar Wang <wxt@rock-chips.com>
Change-Id: I54426d8e30ab4d4f9ca2f9477d780d797e56bfce