s390/mm: remove unused get_page_state() function
Remove unused get_page_state() function:

arch/s390/mm/page-states.c:61:29:
  error: unused function 'get_page_state' [-Werror,-Wunused-function]

Signed-off-by: Heiko Carstens <hca@linux.ibm.com>
Signed-off-by: Alexander Gordeev <agordeev@linux.ibm.com>