MIPS: lantiq: falcon: sysctrl: remove unused falcon_trigger_hrst()
This is a defined but unused function. Fix warning:

arch/mips/lantiq/falcon/sysctrl.c:75:6: error: no previous prototype for 'falcon_trigger_hrst' [-Werror=missing-prototypes]
   75 | void falcon_trigger_hrst(int level)
      |      ^~~~~~~~~~~~~~~~~~~

Signed-off-by: Shiji Yang <yangshiji66@outlook.com>
Signed-off-by: Thomas Bogendoerfer <tsbogend@alpha.franken.de>