drivers: rkflash: Update to SFTL version: 5.0.58 20220814
1.Check the data in second page
2.Fix V7-T:
undefined reference to `__stack_chk_guard' .. undefined reference to `__stack_chk_fail'

Change-Id: Ie494a6c0898fdc58601c4db925afbc5ba1a7e09e
Signed-off-by: Jon Lin <jon.lin@rock-chips.com>