HSI: omap_ssi_port: remove set but unused variables
W=1 build warns that these are set and unused. eg:

error: variable ‘mode’ set but not used
[-Werror=unused-but-set-variable]

Signed-off-by: Rosen Penev <rosenp@gmail.com>
Link: https://patch.msgid.link/20260401215618.11251-1-rosenp@gmail.com
Signed-off-by: Sebastian Reichel <sebastian.reichel@collabora.com>