drm/bridge: sii902x: select VIDEOMODE_HELPERS
aarch64-none-linux-gnu-ld: drivers/gpu/drm/bridge/sii902x.o: in function `sii902x_set_embedded_sync':
drivers/gpu/drm/bridge/sii902x.c:473: undefined reference to `drm_display_mode_to_videomode'

Fixes: a14c198318ac ("drm/bridge: sii902x: add YUV422 input support")
Signed-off-by: Tao Huang <huangtao@rock-chips.com>
Change-Id: I770ae0f4cf3d50a90b881eb3fe074ce57d2db3ac