video: rockchip: rga3: set vfs-only exports into their own namespace
According to gki commit d483eed85ffb ("ANDROID: GKI: set vfs-only exports into their own namespace").

ERROR: modpost: module rga3 uses symbol kernel_write from namespace VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver, but does not import it.
ERROR: modpost: module rga3 uses symbol filp_open from namespace VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver, but does not import it.

Signed-off-by: Tao Huang <huangtao@rock-chips.com>
Change-Id: Ib2f4958b5f7959bfd47982a4d3330f4290a70db2