Revert "staging: android: binder: Fix build warnings"
This reverts commit aecff9d0c1a87b5cd9af1c91b79a3d8fba82ffba.

Changes to the binder code makes this obsolete, and this now causes
the following warnings:

drivers/staging/android/./binder_trace.h:162:21: error: assignment makes integer from pointer without a cast [-Werror]
   __entry->node_ptr = (void __user *)node->ptr;

drivers/staging/android/./binder_trace.h: In function ‘ftrace_raw_event_binder_transaction_ref_to_node’:
drivers/staging/android/./binder_trace.h:188:21: error: assignment makes integer from pointer without a cast [-Werror]
   __entry->node_ptr = (void __user *)ref->node->ptr;

Reported-by: Sherman Yin <syin@broadcom.com>
Signed-off-by: John Stultz <john.stultz@linaro.org>