clk/rockchip/regmap: Add missing MODULE_LICENSE()
Fix build error:
ERROR: modpost: missing MODULE_LICENSE() in
drivers/clk/rockchip/regmap/clk-rockchip-regmap.o

Signed-off-by: Tao Huang <huangtao@rock-chips.com>
Change-Id: Ic21ad1e5b9c90a91ce5b4538ba24f8b4dcbf55f9