include/uapi/linux/rk_vcm_head.h: do not leak CONFIG_COMPAT to userspace
error: include/uapi/linux/rk_vcm_head.h: leak CONFIG_COMPAT to user-space

Fixes: 3c60ce272554 ("media: move rk_vcm_head.h from drivers/media/i2c/ to include/uapi/linux/")
Signed-off-by: Tao Huang <huangtao@rock-chips.com>
Change-Id: I64a4ef35c25fd11997689575059ae0b7ee90369a