soc: rockchip: iomux fix compile error
The commit 5e0fa7cfeff2 ("pinctrl/rockchip: Sync with upstream") removed
the gpio head file from pinctrl-rockchip head file, but the iomux driver
depends on the gpio head file.

  CC      drivers/soc/rockchip/iomux.o
In file included from drivers/soc/rockchip/iomux.c:18:
drivers/soc/rockchip/../../pinctrl/pinctrl-rockchip.h:338:20: error: field has incomplete type 'struct gpio_chip'
        struct gpio_chip                gpio_chip;
                                        ^
drivers/soc/rockchip/../../pinctrl/pinctrl-rockchip.h:338:9: note: forward declaration of 'struct gpio_chip'
        struct gpio_chip                gpio_chip;
               ^
drivers/soc/rockchip/../../pinctrl/pinctrl-rockchip.h:339:28: error: field has incomplete type 'struct pinctrl_gpio_range'
        struct pinctrl_gpio_range       grange;
                                        ^
drivers/soc/rockchip/../../pinctrl/core.h:17:8: note: forward declaration of 'struct pinctrl_gpio_range'
struct pinctrl_gpio_range;
       ^
In file included from drivers/soc/rockchip/iomux.c:18:
drivers/soc/rockchip/../../pinctrl/pinctrl-rockchip.h:430:24: error: field has incomplete type 'enum pin_config_param'
        enum pin_config_param param;
                              ^
drivers/soc/rockchip/../../pinctrl/pinctrl-rockchip.h:425:6: note: forward declaration of 'enum pin_config_param'
enum pin_config_param;
     ^
drivers/soc/rockchip/../../pinctrl/pinctrl-rockchip.h:467:23: error: field has incomplete type 'struct pinctrl_desc'
        struct pinctrl_desc             pctl;
                                        ^
drivers/soc/rockchip/../../pinctrl/core.h:44:9: note: forward declaration of 'struct pinctrl_desc'
        struct pinctrl_desc *desc;
               ^
4 errors generated.

Change-Id: Ib9596eafe1d128de9be4b4d8462ec92842f7ff3f
Signed-off-by: Jianqun Xu <jay.xu@rock-chips.com>