input: touchscreen: elan5515: set vfs-only exports into their own namespace
According to gki commit d483eed85ffb ("ANDROID: GKI: set vfs-only exports into their own namespace").

ERROR: modpost: module tp_elan_5515 uses symbol filp_open from namespace VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver, but does not import it.

Signed-off-by: Tao Huang <huangtao@rock-chips.com>
Change-Id: I22f2fd565c01e804d1e252d6a33dcb62a7b73f62