Revert "ANDROID: arm64: smp: fix Lockdep warning: RCU used illegally from idle CPU."
This reverts commit 4af50419dbc04512c2ca6c2085a2bf6b4a397541.

This patch for an unused/undefined hook causes a kernelci build break:

arch/arm64/kernel/smp.c:885:3: error: implicit declaration of function
‘trace_android_vh_ipi_stop_rcuidle’

The hook is not even defined anywhere so there is no reason to carry it.

Fixes: 4af50419dbc0 ("ANDROID: arm64: smp: fix Lockdep warning: RCU used illegally from idle CPU.")

Change-Id: I59989920dd76db589cc9aa0d01ba1c740ea6c8d5
Signed-off-by: Todd Kjos <tkjos@google.com>