drm/omap: fix compile error when DPI is disabled
When CONFIG_OMAP2_DSS_DPI is disabled, compilation fails due to:

drivers/gpu/drm/omapdrm/dss/dss.h:388:25: error: conflicting types for ‘port’
     struct device_node *port,
                         ^~~~

Fix this by renaming the first parameter correctly.

Signed-off-by: Tomi Valkeinen <tomi.valkeinen@ti.com>