lkl: disable dpdk build for circle ci
Current linux-headers on circle ci, based on linux 4.15.0, doesn't allow
us to build dpdk-17.02 and needs to bump the dpdk version to more recent
one.  But it's not trivial to upgrade this thus temporary disabled for a
while.

The specific compilation error of dpdk-17.02 is:
 error: implicit declaration of function 'pci_enable_msix'

Signed-off-by: Hajime Tazaki <thehajime@gmail.com>