drivers: rkflash: Update to SFTL version: 5.0.58 20220814
Fix V7:
undefined reference to `__stack_chk_guard'

Change-Id: Ie7b7cf74d16fb058acbad63c86c9ad8d9543032e
Signed-off-by: Jon Lin <jon.lin@rock-chips.com>