net: stmmac: dwmac-rk: Fix the following error
ERROR: "dwmac_rk_create_loopback_sysfs" [drivers/net/ethernet/stmicro/stmmac/dwmac-rk.ko] undefined!
ERROR: "stmmac_mdio_reset" [drivers/net/ethernet/stmicro/stmmac/dwmac-rk-tool.ko] undefined!

Fixes: a442177046f0 ("net: ethernet: stmicro: stmmac: Add loopback interface for rockchip")
Signed-off-by: David Wu <david.wu@rock-chips.com>
Change-Id: I493902ea828a81b49cb364959495634c39d7e307