net: phy: rk630phy: Fix typo
drivers/net/phy/rk630phy.c:388:27: error: use of undeclared identifier 'rockchip_phy_tbl';
MODULE_DEVICE_TABLE(mdio, rockchip_phy_tbl);

Fixes: f5f864ab5186 ("driver: rk630: Add RK630 MAC PHY support")
Signed-off-by: Tao Huang <huangtao@rock-chips.com>
Change-Id: I22a5805014cde850e77f493c4f56833a3d96bde5