usb: dwc_otg_310: remove warning
Remove check tool warning of jenkins, smatch and coccinelle in
the dwc_otg_310 driver.

[smatch] drivers/usb/dwc_otg_310/dwc_otg_attr.c:407
error: we previously assumed 'pdev' could be null (see line 404)
[smatch] drivers/usb/dwc_otg_310/dwc_otg_attr.c:415
error: we previously assumed 'pdev' could be null (see line 412)
[coccinelle] drivers/usb/dwc_otg_310/dwc_otg_attr.c:468
WARNING comparing pointer to 0
[coccinelle] drivers/usb/dwc_otg_310/dwc_otg_attr.c:501
WARNING comparing pointer to 0
[smatch] drivers/usb/dwc_otg_310/dwc_otg_cil.c:778
error: buffer overflow 'core_if->core_global_regs->dtxfsiz' 15 <= 15
[smatch] drivers/usb/dwc_otg_310/dwc_otg_cil.c:938
error: buffer overflow 'core_if->core_global_regs->dtxfsiz' 15 <= 15
[coccinelle] drivers/usb/dwc_otg_310/dwc_otg_cil.c:3687
WARNING: possible condition with no effect (if == else)
[smatch] drivers/usb/dwc_otg_310/dwc_otg_cil.c:4182
warn: impossible condition '(deptsiz.b.pktcnt > 1023) => (0-1023 > 1023)'
[smatch] drivers/usb/dwc_otg_310/dwc_otg_cil.c:4316
warn: impossible condition '(deptsiz.b.pktcnt > 1023) => (0-1023 > 1023)'
[coccinelle] drivers/usb/dwc_otg_310/dwc_otg_cil_intr.c:329
Unneeded semicolon
[smatch] drivers/usb/dwc_otg_310/dwc_otg_cil_intr.c:829
warn: was && intended here instead of ||?
[smatch] drivers/usb/dwc_otg_310/dwc_otg_cil_intr.c:949
error: uninitialized symbol 'retval'.
[smatch] drivers/usb/dwc_otg_310/dwc_otg_cil_intr.c:1344
warn: we tested 'core_if->otg_ver == 1' before and it was 'true'
[coccinelle] drivers/usb/dwc_otg_310/dwc_otg_driver.c:555
WARNING: possible condition with no effect (if == else)
[smatch] drivers/usb/dwc_otg_310/dwc_otg_hcd_linux.c:480
error: potential null dereference 'hcd'.  (usb_create_hcd returns null)
[smatch] drivers/usb/dwc_otg_310/dwc_otg_hcd_linux.c:484
warn: variable dereferenced before check 'hcd' (see line 480)
[smatch] drivers/usb/dwc_otg_310/dwc_otg_hcd_linux.c:571
error: potential null dereference 'hcd'.  (usb_create_hcd returns null)
[smatch] drivers/usb/dwc_otg_310/dwc_otg_hcd_linux.c:575
warn: variable dereferenced before check 'hcd' (see line 571)
[coccinelle] drivers/usb/dwc_otg_310/dwc_otg_hcd_linux.c:815
Unneeded semicolon
[smatch] drivers/usb/dwc_otg_310/dwc_otg_pcd.c:1490
warn: this array is probably non-NULL. 'desc->wMaxPacketSize'
[coccinelle] drivers/usb/dwc_otg_310/dwc_otg_pcd.c:2277
WARNING comparing pointer to 0
[coccinelle] drivers/usb/dwc_otg_310/dwc_otg_pcd.c:2277
WARNING comparing pointer to 0
[coccinelle] drivers/usb/dwc_otg_310/usbdev_bc.c:102
WARNING: casting value returned by memory allocation function to
(uoc_field_t *) is useless.
[smatch] drivers/usb/dwc_otg_310/usbdev_bc.c:105
error: potential null dereference 'pBC_UOC_FIELDS'.  (kzalloc returns null)
[coccinelle] drivers/usb/dwc_otg_310/usbdev_bc.c:
WARNING: casting value returned by memory allocation function to
(uoc_field_t *) is useless.
[smatch] drivers/usb/dwc_otg_310/usbdev_bc.c:126
error: potential null dereference 'pBC_UOC_FIELDS'.  (kzalloc returns null)
[coccinelle] drivers/usb/dwc_otg_310/usbdev_bc.c:137 uoc_init_inno()
WARNING: casting value returned by memory allocation function to
(uoc_field_t *) is useless.
[smatch] drivers/usb/dwc_otg_310/usbdev_bc.c:141
error: potential null dereference 'pBC_UOC_FIELDS'.  (kzalloc returns null)
CHECK: Avoid CamelCase: <pBC_UOC_FIELDS>
+	pBC_UOC_FIELDS = kzalloc(SYNOP_BC_MAX * sizeof(uoc_field_t),
WARNING: Prefer kcalloc over kzalloc with multiply
+	pBC_UOC_FIELDS = kzalloc(SYNOP_BC_MAX * sizeof(uoc_field_t),
+				 GFP_ATOMIC);

Change-Id: If4831151464eeaf0e399a4be3c179c4a56e28dde
Signed-off-by: Meng Dongyang <daniel.meng@rock-chips.com>