soc: qcom: ramp_controller: Include linux/bitfield.h
Building ramp_controller under x86_64 results in the following build
error:

error: implicit declaration of function 'FIELD_PREP' is invalid in C99

Include linux/bitfield.h to ensure FIELD_PREP() is declared.

Signed-off-by: Bjorn Andersson <andersson@kernel.org>