soc: rockchip: power-domain: Add missing dummy definition for pd on/off and pd status
Fixes a build break when CONFIG_ROCKCHIP_PM_DOMAINS is not selected.

drivers/video/rockchip/mpp/mpp_common.c:2286:13: error: implicit declaration of function 'rockchip_pmu_pd_is_on' [-Werror,-Wimplicit-function-declaration]
        pd_is_on = rockchip_pmu_pd_is_on(mpp->dev);
                   ^
drivers/video/rockchip/mpp/mpp_common.c:2288:3: error: implicit declaration of function 'rockchip_pmu_pd_on' [-Werror,-Wimplicit-function-declaration]
                rockchip_pmu_pd_on(mpp->dev);
                ^
drivers/video/rockchip/mpp/mpp_common.c:2304:3: error: implicit declaration of function 'rockchip_pmu_pd_off' [-Werror,-Wimplicit-function-declaration]
                rockchip_pmu_pd_off(mpp->dev);
                ^

Fixes: 93993a9497ed ("soc: rockchip: power-domain: export pd on/off and pd status")
Signed-off-by: Tao Huang <huangtao@rock-chips.com>
Change-Id: Idd4039639fb0884a6fccdec0e22f37888a301a98