ASoC: rockchip: multicodecs: Fix the build as module
ERROR: "snd_card_locked" [sound/soc/rockchip/snd-soc-rockchip-multicodecs.ko] undefined!

Fixes: 49950d606ad7 ("ASoC: rockchip: multicodecs: add support property 'rockchip,wait-card-locked'")
Signed-off-by: Tao Huang <huangtao@rock-chips.com>
Change-Id: I71b9ec38072d1a0147ad0f9c3b6198f89aa385ec