ANDROID: GKI: fix build error on 32bits due to ASoC msm change
Commit dbad92f6e8b6 ("ANDROID: GKI: ASoC: msm: fix integer overflow for
long duration offload playback") causes a link error if the kernel is
built for a 32bit target, like i386.

The error is::
	ERROR: "__umoddi3" [sound/soc/intel/atom/snd-soc-sst-atom-hifi2-platform.ko] undefined!
	kernel/scripts/Makefile.modpost:108: recipe for target '__modpost' failed

Fix this problem up by doing the division with the internal kernel
function to do so.

Bug: 153747771
Cc: Dhananjay Kumar <dhakumar@codeaurora.org>
Cc: Banajit Goswami <bgoswami@codeaurora.org>
Cc: Meng Wang <mwang@codeaurora.org>
Cc: Will McVicker <willmcvicker@google.com>
Fixes: dbad92f6e8b6 ("ANDROID: GKI: ASoC: msm: fix integer overflow for long duration offload playback")
Signed-off-by: Chih-Wei Huang <cwhuang@linux.org.tw>
Signed-off-by: Greg Kroah-Hartman <gregkh@google.com>
Change-Id: I339bc24c5531c2f0a14e5875728d349f837245f3