lkl: fix compile error after 4.6-rc5 merge
In file included from include/asm-generic/bug.h:4:0,
                 from arch/lkl/include/generated/asm/bug.h:1,
                 from include/linux/bug.h:4,
                 from include/linux/mmdebug.h:4,
                 from include/linux/gfp.h:4,
                 from include/linux/slab.h:14,
                 from kernel/signal.c:13:
kernel/signal.c: In function ‘signals_init’:
include/linux/compiler.h:489:20: error: call to ‘__compiletime_assert_3590’ declared with attribute error: BUILD_BUG_ON failed: __ARCH_SI_PREAMBLE_SIZE != offsetof(struct siginfo, _sifields._pad)
    prefix ## suffix();    \
                    ^
include/linux/compiler.h:494:2: note: in expansion of macro ‘__compiletime_assert’
  __compiletime_assert(condition, msg, prefix, suffix)
  ^
include/linux/compiler.h:506:2: note: in expansion of macro ‘_compiletime_assert’
  _compiletime_assert(condition, msg, __compiletime_assert_, __LINE__)
  ^
include/linux/bug.h:51:37: note: in expansion of macro ‘compiletime_assert’
 #define BUILD_BUG_ON_MSG(cond, msg) compiletime_assert(!(cond), msg)
                                     ^
include/linux/bug.h:75:2: note: in expansion of macro ‘BUILD_BUG_ON_MSG’
  BUILD_BUG_ON_MSG(condition, "BUILD_BUG_ON failed: " #condition)
  ^
kernel/signal.c:3589:2: note: in expansion of macro ‘BUILD_BUG_ON’
  BUILD_BUG_ON(__ARCH_SI_PREAMBLE_SIZE

We need to take into consideration the 64bit alignment for __ARCH_SI_PREAMBLE_SIZE.

Signed-off-by: Octavian Purdila <octavian.purdila@intel.com>