FogBugz #194889: nios2: Export symbol __muldi3
make modules TSE drivers have this error:
ERROR: "__muldi3" [drivers/net/ethernet/altera/altera_tse.ko] undefined!

__muldi3 is a function in libgcc.a. So, we need to export this symbol
for loadable module to use.

Signed-off-by: Ley Foon Tan <lftan@altera.com>