staging: gpib: Fix PCI header include guard
Clang warns (or errors with CONFIG_WERROR=y):

  In file included from drivers/staging/gpib/ines/ines_gpib.c:19:
  drivers/staging/gpib/include/gpib_pci_ids.h:3:9: error: '__GPIB_PCI_IDS_H' is used as a header guard here, followed by #define of a different macro [-Werror,-Wheader-guard]
      3 | #ifndef __GPIB_PCI_IDS_H
        |         ^~~~~~~~~~~~~~~~
  drivers/staging/gpib/include/gpib_pci_ids.h:4:9: note: '__GPIB_LINUX_PCI_IDS_H' is defined here; did you mean '__GPIB_PCI_IDS_H'?
      4 | #define __GPIB_LINUX_PCI_IDS_H
        |         ^~~~~~~~~~~~~~~~~~~~~~
        |         __GPIB_PCI_IDS_H

Fix the define to match the guard like the note suggests, as that is
clearly what was intended here.

Fixes: 6c52d5e3cde2 ("staging: gpib: Add common include files for GPIB drivers")
Signed-off-by: Nathan Chancellor <nathan@kernel.org>
Tested-by: Javier Carrasco <javier.carrasco.cruz@gmail.com>
Link: https://lore.kernel.org/r/20241015-staging-gpib-fix-pci-header-guard-v1-1-dfa45fe8d63f@kernel.org
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>