drivers: remoteproc: Fix build error
Fix below compilation error due to unused function

qcom_rproc.h:60:12: error: unused function
'\''qcom_rproc_set_dtb_firmware'\'' [-Werror,-Wunused-function].

Change-Id: I9a38dee54d0415408d5a940b3c662a566c894d38
Signed-off-by: Naina Mehta <quic_nainmeht@quicinc.com>