KVM: PPC: Book3S HV: remove unused varible
During build testing, we found a error:
  arch/powerpc/kvm/book3s_hv.c:4052:17: error: variable 'loops' set but not used
                unsigned long loops = 0;
1 error generated.

Fix it by removing the unused variable.

Fixes: b4deba5c41e9 ("KVM: PPC: Book3S HV: Implement dynamic micro-threading on POWER8")
Signed-off-by: Alex Shi <alexs@kernel.org>
Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
Link: https://msgid.link/20240816093313.327268-1-alexs@kernel.org