s390/hypfs: remove unused info_blk_hdr__pcpus() function
Remove unused info_blk_hdr__pcpus() function:

arch/s390/hypfs/hypfs_diag.c:71:21:
  error: unused function 'info_blk_hdr__pcpus' [-Werror,-Wunused-function]

Signed-off-by: Heiko Carstens <hca@linux.ibm.com>
Signed-off-by: Alexander Gordeev <agordeev@linux.ibm.com>