lkl: Fix builds without CONFIG_PCI
Currently, LKL cannot be built without selecting CONFIG_PCI. This is
because pci.c is compiled unconditionally even if CONFIG_PCI is not
specified.

	arch/lkl/drivers/pci.c: In function ‘lkl_pci_probe’:
	arch/lkl/drivers/pci.c:219:15: error: implicit declaration of function ‘pci_scan_bus’ [-Wimplicit-function-declaration]
	  219 |         bus = pci_scan_bus(0, &lkl_pci_root_ops, (void *)dev);
	      |               ^~~~~~~~~~~~

This commit fixes the problem by compiling pci.c conditionally. After
this commit, pci.c will only be compiled if CONFIG_PCI is on.

Signed-off-by: Ruihan Li <lrh2000@pku.edu.cn>