LSK-ANDROID: tee: Fix OP-TEE driver build
Add missing header linux/sched.h to fix undeclared functions/variables,
otherwise we run into following build error:

  CC [M]  drivers/tee/optee/rpc.o
drivers/tee/optee/rpc.c: In function 'handle_rpc_func_cmd_wait':
drivers/tee/optee/rpc.c:144:2: error: implicit declaration of function 'set_current_state' [-Werror=implicit-function-declaration]
  set_current_state(TASK_INTERRUPTIBLE);
  ^
drivers/tee/optee/rpc.c:144:20: error: 'TASK_INTERRUPTIBLE' undeclared (first use in this function)
  set_current_state(TASK_INTERRUPTIBLE);
                    ^

Signed-off-by: Amit Pundir <amit.pundir@linaro.org>