LSK-ANDROID: arm64: mm: Fix __create_pgd_mapping() call
Fix AOSP backport of "FROMLIST: arm64: mm: Map entry trampoline
into trampoline and kernel page tables", which is tweaked to
match __create_pgd_mapping() API on android-4.4, but the related
upstream patch is already pushed in LSK commit 3bbd245ee850
("arm64: mm: add param to force create_pgd_mapping() to use page mappings").

Otherwise we run into following build error reported on KernelCI
https://kernelci.org/build/lsk/branch/linux-linaro-lsk-v4.4-android/kernel/lsk-v4.4-17.11-android-844-g6a7d9fbcf946/

arch/arm64/mm/mmu.c:501:2: error: too few arguments to function '__create_pgd_mapping'

Fixes: AOSP Change-Id: I31b2dcdf4db36c3e31181fe43ccb984f9efb6ac6
       ("FROMLIST: arm64: mm: Map entry trampoline into trampoline and kernel page tables")
Signed-off-by: Amit Pundir <amit.pundir@linaro.org>