regulator: wl2868c: Fix typo
drivers/regulator/wl2868c-regulator.c:252:26: error: use of undeclared identifier 'i2c_device_id';
MODULE_DEVICE_TABLE(i2c, i2c_device_id);

Fixes: 7f56984c2172 ("regulator: Add WL2868C LDO support")
Signed-off-by: Tao Huang <huangtao@rock-chips.com>
Change-Id: I66e1d2fc6716c42fccc6e65262b6124dec4d5cf8