ANDROID: fix kernelci issue for allnoconfig builds
'allnoconfig' builds failed with:

kernel/sched/sched.h:1203:50: error: ‘struct rq’ has no member named ‘cpu’

rq->cpu needs to be replaced with cpu_of(rq) for !CONFIG_SMP builds

Fixes: 4442801a43f3 ("ANDROID: sched: Introducing PELT multiplier")
Signed-off-by: Todd Kjos <tkjos@google.com>
Change-Id: Iceb439dc3bba27516b5ecd2c18c9835c23e5a39a