c6x: asm: Add default flat.h according to xtensa architecture
For supporting uClinux flat-format executables, c6x needs to define the
fewest features to support it, at present, xtensa architecture has the
fewest feature for it, so just copy xtensa flat.h. The related error:

    CC      fs/binfmt_flat.o
  In file included from fs/binfmt_flat.c:36:0:
  include/linux/flat.h:12:22: fatal error: asm/flat.h: No such file or directory

Signed-off-by: Chen Gang <gang.chen.5i5j@gmail.com>
Signed-off-by: Mark Salter <msalter@redhat.com>