USB: OHCI: remove bogus #error
The OHCI host controller driver can be built standalone now,
without enabling any of the available bus glue drivers, so
there is not really a reason to error out here:

drivers/usb/host/ohci-hcd.c:1258: error:
 #error "missing bus glue for ohci-hcd"  #error "missing bus glue for ohci-hcd"

This follows the same change done in ehci recently as 843e56c0
"USB: EHCI: remove bogus #error" and hopefully avoids future
merge conflicts in this list.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Acked-by: Alan Stern <stern@rowland.harvard.edu>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit 358e91175cac9398b152ad9adc2391ebce34011c)
Signed-off-by: Ryan Harkin <ryan.harkin@linaro.org>

Conflicts:
	drivers/usb/host/ohci-hcd.c
Signed-off-by: Mark Brown <broonie@linaro.org>